services:
  app:
    build: .
    ports:
      - "3123:3123"
    environment:
      - RDS_HOSTNAME=postgres
      - RDS_USERNAME=AgriTech
      - RDS_PASSWORD=ExtremeFarming2024!
      - RDS_DB_NAME=db
      - RDS_PORT=5432
      - NODE_ENV=development
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent --show-error --output /dev/null http://localhost:3123/healthz"]
      start_period: 3s
      interval: 10s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:17.2
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=AgriTech
      - POSTGRES_PASSWORD=ExtremeFarming2024!
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U AgriTech -d db"]
      start_period: 3s
      interval: 10s
      timeout: 5s
      retries: 3